### ISSUE TITLE
Sponsor email

### ISSUE THREAD

**Issue by aterrel** [scipy-conference/SciPy-2014#44] opened 2014-01-28 22:24 UTC
An email should be sent to the sponsorship chairs when someone uses the sponsor features.

**Comment by brettrmurphy** [comment] 2014-01-28 22:31
I "applied" and could see the email address in the form was mine. I did not add any attachments on the second page of the application and just saved it. It says its "awaiting approval". No email was sent though it seems?

**Comment by codersquid** [comment] 2014-02-08 15:15
Is this still an issue, or was mail sent after we added the cron job? If the root cause was the missing cron job, then when #46 is resolved we can close this.

**Comment by aterrel** [comment] 2014-02-20 16:28
@brettrmurphy Waiting for you to verify this is still a bug.

**Comment by brettrmurphy** [comment] 2014-02-20 16:40
I still have not received a notice. It still says it is "waiting approval"
in there.

-- Brett

Brett Murphy
Enthought, Inc.
bmurphy@enthought.com
512-536-1057

**Comment by aterrel** [comment] 2014-02-20 16:44
I'm deleting. Try to resubmit.

**Closed as completed** 2014-09-20 15:19 UTC
Labels: bug
